[project]
name = "appsettings2"
version = "0.0.0"
description = "Unifies configuration sources into a Configuration object that can be bound to complex types, or accessed directly for configuration data."
authors = [
    { name="Shaun Wilson", email="mrshaunwilson@msn.com" }
]
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Intended Audience :: Developers"
]
requires-python = ">=3.11"
dependencies = [
  "pyyaml>=6.0.2"
]

[project.urls]
Documentation = "https://appsettings2.readthedocs.io/"
Homepage = "https://github.com/wilson0x4d/appsettings2"
Repository = "https://github.com/wilson0x4d/appsettings2.git"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
exclude = [
    "docs",
    "src",
    "src.*",
    "tests",
    "tests.*"
]
